services:
  app-handluz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-handluz
    environment:
      - PORT=3000
      - FORCE_HTTP=true
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - site-network

networks:
  site-network:
    external: true